openapi: 3.0.0
x-stoplight:
  id: gqp8k9iunj5fy
info:
  title: Candidates
  version: '3.0'
servers:
  - url: 'http://api.talent360.io/account/candidates'
paths:
  '/export/candidates/new/{date}':
    parameters:
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Get all new candidates by date
      tags:
        - Export
      responses: {}
      operationId: get-export-new-date
  '/export/candidates/modified/{date}':
    parameters:
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Get all modified Candidates by date
      tags:
        - Export
      responses: {}
      operationId: get-export-modified-date
  '/export/candidates/deleted/{date}':
    parameters:
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Get all Candidates to delete by date
      tags:
        - Export
      responses: {}
      operationId: get-export-deleted-date
  '/export/documents/new/{date}':
    parameters:
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-export-documents-new-date
  '/export/documents/modified/{date}':
    parameters:
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-export-documents-modified-date
  '/export/documents/deleted/{date}':
    parameters:
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-export-documents-deleted-date
  '/export/documents/{documentId}':
    parameters:
      - schema:
          type: string
        name: documentId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-export-documents-documentId
components:
  schemas: {}
tags:
  - name: Export
